### ISSUE TITLE
Github Project Kanban Board Setup

### ISSUE THREAD

**Issue by melaniesigrid** [melaniesigrid/AstronomyPictureOfTheDay#21]
Hello! Thank you for reviewing this issue.

This is the link to our project repo:
https://github.com/melaniesigrid/AstronomyPictureOfTheDay

There are 2 people on our team: @IbrohimRasulov and @melaniesigrid. 

<img src="https://media4.giphy.com/media/EktbegF3J8QIo/giphy.gif"/>

**Comment by BrianSammit** [comment]
# STATUS: APROVED :green_circle: :clap: 

Hello @melaniesigrid  and   @IbrohimRasulov, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
